# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  - task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
#- task: PublishBuildArtifacts@1
#  displayName: 'Publish artifacts: drop'
#  inputs:
#   publishLocation: Container
#   PathtoPublish: $(Build.ArtifactStagingDirectory)
- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy: atulvotingapp'
  inputs:
    azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
    appType: webAppLinux
    appName: reactappyaml
    runtimeStack: 'NODE|10.10'
    package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    startUpCommand: 'npm run start'
